---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.15.9  #No exemplo estou apontando para o IP local do meu cluster para utilizar o LoadBalancer
  ports:
  - name: http
    port: 3000
    targetPort: 8000
  selector:
    name: go-app